2023-12-12 22:30:54,177 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, default_file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 39, in __init__
    self.init()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 121, in init
    self.saveinput = TextInput(text=self.default_file_name, multiline=False, size_hint_y=None, height=btn_height)
AttributeError: 'SaveFileDialog' object has no attribute 'default_file_name'

2023-12-12 22:31:27,725 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, default_file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 39, in __init__
    self.init()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 121, in init
    self.saveinput = TextInput(text=self.default_file_name, multiline=False, size_hint_y=None, height=btn_height)
AttributeError: 'SaveFileDialog' object has no attribute 'default_file_name'

2023-12-12 22:31:49,092 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, default_file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 39, in __init__
    self.init()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 121, in init
    self.saveinput = TextInput(text=self.default_file_name, multiline=False, size_hint_y=None, height=btn_height)
AttributeError: 'SaveFileDialog' object has no attribute 'default_file_name'

2023-12-12 22:33:35,165 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "kivy\_event.pyx", line 235, in kivy._event.EventDispatcher.__init__
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, default_file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 34, in __init__
    super(OpenFileDialog, self).__init__(**kwargs)
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\modalview.py", line 195, in __init__
    super(ModalView, self).__init__(**kwargs)
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
    super(AnchorLayout, self).__init__(**kwargs)
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\widget.py", line 357, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy\_event.pyx", line 238, in kivy._event.EventDispatcher.__init__
TypeError: Properties ['default_file_name'] passed to __init__ may not be existing property names. Valid properties are ['_anim_alpha', '_anim_duration', '_container', '_is_open', '_window', 'anchor_x', 'anchor_y', 'attach_to', 'auto_dismiss', 'background', 'background_color', 'border', 'center', 'center_x', 'center_y', 'children', 'cls', 'content', 'disabled', 'height', 'ids', 'motion_filter', 'opacity', 'overlay_color', 'padding', 'parent', 'pos', 'pos_hint', 'right', 'separator_color', 'separator_height', 'size', 'size_hint', 'size_hint_max', 'size_hint_max_x', 'size_hint_max_y', 'size_hint_min', 'size_hint_min_x', 'size_hint_min_y', 'size_hint_x', 'size_hint_y', 'title', 'title_align', 'title_color', 'title_font', 'title_size', 'top', 'width', 'x', 'y']

2023-12-12 22:34:48,322 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 39, in __init__
    self.init()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 121, in init
    self.saveinput = TextInput(text=self.file_name, multiline=False, size_hint_y=None, height=btn_height)
AttributeError: 'SaveFileDialog' object has no attribute 'file_name'

2023-12-12 22:38:15,620 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 345, in save_to_file
    SaveFileDialog("请输入保存文件名", fun=ff, default_dir=save_dir, file_name=default_file_name).open()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 107, in __init__
    super(SaveFileDialog, self).__init__(title, fun, default_dir, **kwargs)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 39, in __init__
    self.init()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 121, in init
    self.saveinput = TextInput(text=self.file_name, multiline=False, size_hint_y=None, height=btn_height)
AttributeError: 'SaveFileDialog' object has no attribute 'file_name'

2023-12-12 22:41:11,202 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 200, in pai_pan
    self.step2()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 366, in step2
    self.gongs.get(location).append_start(dou_shu_stars.get(hua_star)(star))
AttributeError: 'NoneType' object has no attribute 'append_start'

2023-12-12 22:42:09,033 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 200, in pai_pan
    self.step2()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 366, in step2
    self.gongs.get(location).append_start(dou_shu_stars.get(hua_star)(star))
AttributeError: 'NoneType' object has no attribute 'append_start'

2023-12-12 22:43:57,923 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 199, in pai_pan
    self.step1()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 217, in step1
    gong_tian_gan = Shi_Er_Gong_Tian_Gan(self.pan_time.ntg)
  File "D:\pycharm\pythonProject1\wsl\tianji\config\shi_er_gong_tian_gan_biao_module.py", line 31, in __init__
    raise Exception(f"指定了不存在的天干 =>  {nian_gan}")
Exception: 指定了不存在的天干 =>  癸

2023-12-12 22:44:38,316 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 199, in pai_pan
    self.step1()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 217, in step1
    gong_tian_gan = Shi_Er_Gong_Tian_Gan(self.pan_time.ntg)
  File "D:\pycharm\pythonProject1\wsl\tianji\config\shi_er_gong_tian_gan_biao_module.py", line 31, in __init__
    raise Exception(f"指定了不存在的天干 =>  {nian_gan}")
Exception: 指定了不存在的天干 =>  癸

2023-12-12 22:46:52,249 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 199, in pai_pan
    self.step1()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 217, in step1
    gong_tian_gan = Shi_Er_Gong_Tian_Gan(self.pan_time.ntg)
  File "D:\pycharm\pythonProject1\wsl\tianji\config\shi_er_gong_tian_gan_biao_module.py", line 27, in __init__
    t = tian_gan_iter.next()
AttributeError: 'NoneType' object has no attribute 'next'

2023-12-12 22:51:53,342 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 202, in pai_pan
    self.step4()  # 安流年星，现在是按出生年安
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 380, in step4
    for star, location in sub_dic.items():
AttributeError: 'str' object has no attribute 'items'

2023-12-12 22:53:49,215 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 202, in pai_pan
    self.step4()  # 安流年星，现在是按出生年安
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 380, in step4
    for star, location in sub_dic.items():
AttributeError: 'str' object has no attribute 'items'

2023-12-12 22:56:48,510 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 193, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 202, in pai_pan
    self.step4()  # 安流年星，现在是按出生年安
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 380, in step4
    for star, location in sub_dic.items():
AttributeError: 'str' object has no attribute 'items'

2023-12-12 23:17:46,912 - D:\pycharm\pythonProject1\wsl\main.py[line:89] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 85, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\Dialog.py", line 68, in select_file
    self.fun(file)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 368, in update_user_info
    self.start(None)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 293, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 195, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 204, in pai_pan
    self.step4()  # 安流年星，现在是按出生年安
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPan.py", line 377, in step4
    ndz = self.pan_time.liu_nian_ba_zi[1]  # 流年地支
TypeError: 'method' object is not subscriptable

2023-12-13 00:01:38,302 - D:\pycharm\pythonProject1\wsl\main.py[line:90] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 86, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
TypeError: MingPanDate.__init__.<locals>.<lambda>() takes 0 positional arguments but 1 was given

2023-12-13 00:03:48,696 - D:\pycharm\pythonProject1\wsl\main.py[line:90] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 86, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 925, in _run_prepare
    root = self.build()
  File "D:\pycharm\pythonProject1\wsl\main.py", line 67, in build
    app = AppScreen(self.stop)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\AppScreenUI.py", line 32, in __init__
    self.user = MingPanDate(self)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 99, in __init__
    on_release=self.pan_windows.self.exit_fun)
AttributeError: 'AppScreen' object has no attribute 'self'

2023-12-13 11:35:00,583 - D:\pycharm\pythonProject1\wsl\main.py[line:94] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 90, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 75, in on_start
    if kivy._get_platform() == "win":
AttributeError: module 'kivy' has no attribute '_get_platform'

2023-12-13 11:44:08,987 - D:\pycharm\pythonProject1\wsl\main.py[line:96] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 92, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 75, in on_start
    self.root_window.exit_fullscreen()
AttributeError: 'WindowSDL' object has no attribute 'exit_fullscreen'

2023-12-13 11:46:09,128 - D:\pycharm\pythonProject1\wsl\main.py[line:96] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 92, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 75, in on_start
    self.root_window.exit_fullscreen()
AttributeError: 'WindowSDL' object has no attribute 'exit_fullscreen'

2023-12-13 11:48:12,859 - D:\pycharm\pythonProject1\wsl\main.py[line:94] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 90, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 75, in on_start
    if kivy._get_platform() == "win":
AttributeError: module 'kivy' has no attribute '_get_platform'

2023-12-13 11:49:00,506 - D:\pycharm\pythonProject1\wsl\main.py[line:94] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 90, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 75, in on_start
    if kivy.kivy_options._get_platform() == "win":
AttributeError: 'dict' object has no attribute '_get_platform'

2023-12-13 11:51:36,845 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 925, in _run_prepare
    root = self.build()
  File "D:\pycharm\pythonProject1\wsl\main.py", line 70, in build
    app = AppScreen(self.root_window.show_about())
AttributeError: 'NoneType' object has no attribute 'show_about'

2023-12-13 11:58:04,122 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 950, in _run_prepare
    self.dispatch('on_start')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\main.py", line 76, in on_start
    if kivy.kivy_options._get_platform() == "win":
AttributeError: 'dict' object has no attribute '_get_platform'

2023-12-13 12:27:31,785 - D:\pycharm\pythonProject1\wsl\main.py[line:97] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 93, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 925, in _run_prepare
    root = self.build()
  File "D:\pycharm\pythonProject1\wsl\main.py", line 71, in build
    app = AppScreen(self)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\AppScreenUI.py", line 31, in __init__
    self.exit_fun=app.exit_fun
AttributeError: 'PhoneApp' object has no attribute 'exit_fun'

2023-12-13 12:29:00,919 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 925, in _run_prepare
    root = self.build()
  File "D:\pycharm\pythonProject1\wsl\main.py", line 70, in build
    app = AppScreen()
TypeError: AppScreen.__init__() missing 1 required positional argument: 'app'

2023-12-13 12:56:46,221 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
TypeError: 'NoneType' object is not callable

2023-12-13 16:04:37,615 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\GongScreenUI.py", line 96, in <lambda>
    button.on_release =lambda : message_popup(res[1].info).open()
AttributeError: 'NoneType' object has no attribute 'open'

2023-12-13 18:46:36,772 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 310, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 71, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 78, in pai_pan
    self.step2()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 114, in step2
    self.gongs.get(zi_wei_location).append_start(dou_shu_stars.get("紫薇"))
AttributeError: 'NoneType' object has no attribute 'append_start'

2023-12-13 18:51:11,955 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 310, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 71, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 77, in pai_pan
    self.step1()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 102, in step1
    res = wx.get_wu_xing()
  File "D:\pycharm\pythonProject1\wsl\tianji\config\wu_xing_jv_biao_module.py", line 188, in get_wu_xing
    for k,v in wu_xing_list:
TypeError: cannot unpack non-iterable int object

2023-12-13 18:51:26,101 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 310, in start
    p = Pan(ming_pan_time, self.gender)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 71, in __init__
    self.pai_pan()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 78, in pai_pan
    self.step2()
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\MingPanScreenUI.py", line 114, in step2
    self.gongs.get(zi_wei_location).append_start(dou_shu_stars.get("紫薇"))
AttributeError: 'NoneType' object has no attribute 'append_start'

2023-12-13 20:24:08,349 - D:\pycharm\pythonProject1\wsl\main.py[line:95] - ERROR: Traceback (most recent call last):
  File "D:\pycharm\pythonProject1\wsl\main.py", line 91, in <module>
    app.run()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 383, in idle
    self.dispatch_input()
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 334, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "D:\pythonENV\Anaconda3\envs\appENV\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\UserUI.py", line 312, in start
    self.pai_pan(p)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\AppScreenUI.py", line 110, in pai_pan
    self.update_gua(ming_pan)
  File "D:\pycharm\pythonProject1\wsl\tianji\ui\AppScreenUI.py", line 118, in update_gua
    day_bazi[0]=ming_pan.current_year_ntg
AttributeError: 'Pan' object has no attribute 'current_year_ntg'

